title: Theses
description: Website for Bachelor's and Master's theses (offered by Gerit Wagner)
theme: just-the-docs

url: https://just-the-docs.github.io

repository: digital-work-lab/theses

gh_edit_link: true
gh_edit_link_text: 'Help improve this page'
gh_edit_repository: 'https://github.com/digital-work-lab/theses'
gh_edit_branch: 'main'
gh_edit_view_mode: 'tree'

search:
    focus_shortcut_key: 'k'

logo: "/assets/images/theses.png"

mermaid:
  version: "11.4.0"

callouts:
  warning:
    title: Warning
    color: red
  call_for_theses:
    title: "Info: Call for theses"
    color: yellow
  info:
    title: "Info"
    color: yellow

aux_links:
  "Repository":
    - "https://github.com/digital-work-lab/theses"
  "Improvement":
    - "https://github.com/digital-work-lab/theses/issues"
